### ISSUE TITLE
Arun tracking steps while learning Github

### ISSUE THREAD

**Issue by aramaniart** [githubschool/refactored-fiesta#18]
- [x] branch off of master
- [x] create commits on our new branch
- [x] open a PR on GitHub
- [x] _code review_ + collaboration
- [x] merge when we receive 👍
